# Default values for cirrus-webgui4db
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# See: Cirrus-WebGui4Db/networking/charts/cirrus-webgui4db/values.yaml
# to know all variables
#
webApp:

  ingress:
    annotations:
    #  cert-manager.io/issuer: "letsencrypt-prod"
    hosts:
      - host: localhost
      #- host: myDomain.com
        paths:
          - path: /cirrus-webgui4db/
            pathType: Prefix
    # tls:
    #  - secretName: letsencrypt-tls
    #    hosts:
    #      - myDomain.com

serviceGateway:

  ingress:
    hosts:
      - host: localhost
      # - host: myDomain.com
        paths:
          - path: /cirrus-webgui4db-gateway(/|$)(.*)
            pathType: Prefix
    # tls:
    #  - secretName: letsencrypt-tls
    #    hosts:
    #      - myDomain.com
