# Default values for cirrus-webgui4db
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# See: Cirrus-WebGui4Db/networking/charts/cirrus-webgui4db/values.yaml
# to know all variables
#
webApp:

  ingress:
    hosts:
      - host: localhost
      #- host: myDomain.com

    # tls:
    #  - secretName: letsencrypt-tls
    #    hosts:
    #      - myDomain.com

serviceMongoDb:

  ingress:
    hosts:
      - host: localhost
      # - host: myDomain.com

    # tls:
    #  - secretName: letsencrypt-tls
    #    hosts:
    #      - myDomain.com