# Default values for cirrus-webgui4db
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# See: Cirrus-WebGui4Db/networking/charts/cirrus-webgui4db/values.yaml
# to know all variables
#
webApp:
  ingress:
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
    hosts:
      #- host: localhost
      - host: begin-diaz.freeboxos.fr
        paths:
        ## SEE file: "webApp/Dockerfile", line:2 COPY build/ /usr/share/nginx/html/cirrus-webgui4db
          - path: /cirrus-webgui4db/
            pathType: Prefix
    tls:
      - secretName: cirrus-tls
        hosts:
          - begin-diaz.freeboxos.fr

serviceGateway:
  ingress:
    hosts:
      #- host: localhost
      - host: begin-diaz.freeboxos.fr
        paths:
        ## SEE file: ".env.production", line:4 REACT_APP_SERVICE_ROUTE=cirrus-webgui4db-gateway/
          - path: /cirrus-webgui4db-gateway/
            pathType: Prefix
    tls:
      - secretName: cirrus-tls
        hosts:
          - begin-diaz.freeboxos.fr
