apiVersion: v1
kind: Service
metadata:
  name: {{ include "cirrus-service-gateway.fullname" . }}
  labels:
    {{- include "cirrus-webgui4db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceGateway.service.type }}
  ports:
    - port: {{ .Values.serviceGateway.service.port }}
      targetPort: 3000
      protocol: TCP
      name: main
  selector:
    {{- include "cirrus-webgui4db.selectorLabels" . | nindent 4 }}
