apiVersion: v1
kind: Service
metadata:
  name: {{ include "cirrus-webgui4db.fullname" . }}
  labels:
    {{- include "cirrus-webgui4db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webApp.service.type }}
  ports:
    - port: {{ .Values.webApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cirrus-webgui4db.selectorLabels" . | nindent 4 }}
