apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cirrus-service-mongodb.fullname" . }}
  labels:
    {{- include "cirrus-webgui4db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.serviceMongoDb.autoscaling.enabled }}
  replicas: {{ .Values.serviceMongoDb.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cirrus-webgui4db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.serviceMongoDb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cirrus-webgui4db.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.serviceMongoDb.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cirrus-service-mongodb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.serviceMongoDb.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.serviceMongoDb.securityContext | nindent 12 }}
          image: "{{ .Values.serviceMongoDb.image.repository }}"
          imagePullPolicy: {{ .Values.serviceMongoDb.image.pullPolicy }}
          ports:
            - name : service-port
              containerPort: 3000   ## see Dockerfile.mongodb SERVICE_PORT="3000"
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: service-port
            initialDelaySeconds: 5
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: service-port
            initialDelaySeconds: 5
            periodSeconds: 20

          env:
          - name: SERVICE_HOST
            value: "0.0.0.0"  ## see Dockerfile.mongodb SERVICE_HOST="0.0.0.0"
          - name: SERVICE_PORT
            value: "3000"     ## see Dockerfile.mongodb SERVICE_PORT="3000"

          resources:
            {{- toYaml .Values.serviceMongoDb.resources | nindent 12 }}
      {{- with .Values.serviceMongoDb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMongoDb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMongoDb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
