apiVersion: v1
kind: Service
metadata:
  name: {{ include "cirrus-service-postgresql.fullname" . }}
  labels:
    {{- include "cirrus-service-postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicePostgreSql.service.type }}
  ports:
    - port: {{ .Values.servicePostgreSql.service.port }}
      targetPort: 3000
      protocol: TCP
      name: main
  selector:
    {{- include "cirrus-service-postgresql.selectorLabels" . | nindent 4 }}
